-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.

CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL
);

CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    available BOOLEAN DEFAULT TRUE
);

CREATE TABLE Purchases (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE public.Inventory (
    pid integer NOT NULL,
    price numeric NOT NULL,
    quantity integer NOT NULL,
    sid integer NOT NULL,
    description character varying(255)
);


ALTER TABLE public.inventory OWNER TO hsysr;

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT inventory_pkey PRIMARY KEY (pid, sid);

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT inventory_pid_fkey FOREIGN KEY (pid) REFERENCES public.products(id);

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT inventory_sid_fkey FOREIGN KEY (sid) REFERENCES public.users(id);
